version: '3'
services:
    server:
        image: mytest
        stdin_open: true
        tty: true
        port:
            - '8600:8600'
        volumes:
            - '~/experiment/socket/bin:/home/bin'

    middle1:
        image: mytest
        stdin_open: true
        tty: true
        port:
            - '8600:8600'
            - '8601:8601'
        volumes:
            - '~/experiment/socket/bin:/home/bin'

    middle2:
        image: mytest
        stdin_open: true
        tty: true
        port:
            - '8601:8601'
            - '8602:8602'
        volumes:
            - '~/experiment/socket/bin:/home/bin'

    middle3:
        image: mytest
        stdin_open: true
        tty: true
        port:
            - '8602:8602'
            - '8603:8603'
        volumes:
            - '~/experiment/socket/bin:/home/bin'

    client:
        image: mytest
        stdin_open: true
        tty: true
        port:
            - '8600:8600'
            - '8601:8601'
            - '8602:8602'
            - '8603:8603'
        volumes:
            - '~/experiment/socket/bin:/home/bin'
